# Base stage with Bun runtime
FROM oven/bun:alpine AS base
WORKDIR /app

# Install stage using pnpm for dependency management
FROM base AS builder
RUN apk update && \
    apk add --no-cache npm && \
    npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
COPY apps/rest/package.json ./apps/rest/
COPY packages/db/package.json ./packages/db/
RUN pnpm install --frozen-lockfile

# Release stage for running the application with Bun
FROM base AS release
#COPY --from=install /app/node_modules ./node_modules
COPY apps/rest ./apps/rest
COPY packages/db ./packages/db

ENV NODE_ENV=production
ENV DATABASE_URL=postgres://postgres:123456@db:5432/scraping
ENV REDIS_URL=redis://redis:6379

EXPOSE 3002
CMD ["bun", "run", "apps/rest/src/index.ts"]
