# Base stage with Bun alpine
FROM oven/bun:alpine AS base
WORKDIR /app

# Install stage using pnpm for dependency management
FROM base AS builder
RUN apk update && \
    apk add --no-cache npm && \
    npm install -g pnpm@latest

ENV PNPM_HOME=/pnpm-global
ENV PATH=$PNPM_HOME:$PATH
RUN mkdir -p /root && touch /root/.shrc
ENV ENV=/root/.shrc
ENV SHELL=/bin/sh
# Enable corepack (which comes with Node 16.9+)
RUN corepack enable
# Run pnpm setup to create the global bin directory
RUN pnpm setup
RUN pnpm install turbo --global

COPY . .
RUN turbo prune dashboard --docker

# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update && \
    apk add --no-cache npm && \
    npm install -g pnpm@latest
WORKDIR /app

# First install the dependencies (as they change less often)
COPY --from=builder /app/out/json .
RUN pnpm install

# Build the project
COPY --from=builder /app/out/full/ .

# Uncomment and use build args to enable remote caching
# ARG TURBO_TEAM
# ENV TURBO_TEAM=$TURBO_TEAM

# ARG TURBO_TOKEN
# ENV TURBO_TOKEN=$TURBO_TOKEN

RUN pnpm turbo build

FROM base AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 bunjs
RUN adduser --system --uid 1001 nextjs
USER nextjs

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/apps/dashboard/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/dashboard/.next/static ./apps/dashboard/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/apps/dashboard/public ./apps/dashboard/public

CMD ["bun", "apps/web/server.js"]
